yolo_model:

  config_file:
    name: yolov2-tiny-voc-yu.cfg
  weight_file:
    name: yolov2-tiny-voc_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - ball
      - bottle
